version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "22:43"
      timezone: Asia/Singapore
    target-branch: main
    open-pull-requests-limit: 5
