AuthorizedKeysCommand none
AuthorizedKeysCommandUser nobody
TrustedUserCAKeys none
AuthorizedPrincipalsFile none
AuthorizedPrincipalsCommand none
AuthorizedPrincipalsCommandUser nobody
PermitUserEnvironment no

Match User mochirii-forums-operator
    AuthenticationMethods publickey
    AuthorizedKeysFile /var/lib/mochirii/forums/operator/.ssh/authorized_keys
    ForceCommand none
    DisableForwarding yes
    PermitTTY yes
    PermitUserRC no

Match User mochirii-forums-deploy
    AuthenticationMethods publickey
    AuthorizedKeysFile /var/lib/mochirii/forums/deploy/.ssh/authorized_keys
    ForceCommand /usr/local/libexec/mochirii-forums/ssh-deploy-dispatch.py
    DisableForwarding yes
    PermitTTY no
    PermitUserRC no

Match all
